public with sharing class TestApex {
    
    public static void testName(){
        System.debug('exp change1');
        System.debug('exp change2');
        System.debug('don change0');
        System.debug('master online change0');
        System.debug('master change0');
        System.debug('exp change3');
        System.debug('master change1');
        System.debug('master change2');
        System.debug('master change3');
        System.debug('master change4');
        System.debug('lost1');
        System.debug('lost2');
    }
}
